<a href="#"
   class="mistertango-button-pay"
   data-language="<?php echo Mage::app()->getStore()->getLanguageCode(); ?>"
   data-customer-email="<?php echo $this->getCustomerEmail(); ?>"
   data-amount="<?php echo $this->getGrandTotal(); ?>"
   data-currency="<?php echo $this->getCurrentCurrencyIsoCode(); ?>"
   data-transaction="<?php echo $this->getTransactionId(); ?>">
    <?php echo $this->__('Checkout'); ?> <?php echo $this->getGrandTotal(true); ?>
</a>
